// Command gentorrent writes a small, deterministic, multi-file .torrent
// metainfo file. It is used to produce examples/sample.torrent and the CLI
// test fixture; it exercises the library's own canonical encoder.
//
// Usage: go run ./examples/gentorrent OUT.torrent
package main

import (
	"bytes"
	"crypto/sha1"
	"fmt"
	"os"

	"github.com/Conedope/benode"
)

func pieces(n int) []byte {
	var b bytes.Buffer
	for i := 0; i < n; i++ {
		sum := sha1.Sum([]byte(fmt.Sprintf("benode-sample-piece-%d", i)))
		b.Write(sum[:])
	}
	return b.Bytes()
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: gentorrent OUT.torrent")
		os.Exit(2)
	}
	info := benode.Dict{
		"name":         benode.Bytes("benode-sample"),
		"piece length": benode.Int(262144),
		"pieces":       benode.Bytes(pieces(4)),
		"files": benode.List{
			benode.Dict{
				"length": benode.Int(1234),
				"path":   benode.List{benode.Bytes("README.md")},
			},
			benode.Dict{
				"length": benode.Int(56789),
				"path":   benode.List{benode.Bytes("src"), benode.Bytes("main.go")},
			},
		},
	}
	root := benode.Dict{
		"announce": benode.Bytes("http://tracker.example:6969/announce"),
		"announce-list": benode.List{
			benode.List{benode.Bytes("http://tracker.example:6969/announce")},
			benode.List{
				benode.Bytes("udp://tracker2.example:6969/announce"),
				benode.Bytes("https://tracker3.example/announce"),
			},
		},
		"comment":       benode.Bytes("generated by benode examples/gentorrent"),
		"created by":    benode.Bytes("benode/0.1.0"),
		"creation date": benode.Int(1767225600),
		"info":          info,
	}

	data := benode.Encode(root)
	if err := os.WriteFile(os.Args[1], data, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d bytes)\n", os.Args[1], len(data))
}
